TalkingWall/ViewModels/WallViewModel.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using TalkingWall.Domain;

namespace TalkingWall.ViewModels
{
    public class WallViewModel
    {
        public WallViewModel()
        {
            Name = String.Empty;
            Message = String.Empty;
            Messages = new Collection<WallMessage>();
        }

        public WallViewModel(WallMessage wallMessage, Collection<WallMessage> messageCollection)
        {
            Name = wallMessage.Name;
            Message = wallMessage.Message;
            Messages = messageCollection;
        }
        public string Name { get; set; }
        public string Message { get; set; }
       public Collection<WallMessage> Messages{ get; set; }
    }
}

TalkingWall/Controllers/WallController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalkingWall.Domain;
using TalkingWall.Domain.Services;
using TalkingWall.ViewModels;

namespace TalkingWall.Controllers
{
    public class WallController : Controller
    {
        IWallMessageRepository msgRepo;

        public WallController(IWallMessageRepository messagesRepository)
        {
            msgRepo = messagesRepository;
        }
        


        // GET: Wall
        public ActionResult Index()
        {
            WallViewModel vm = new WallViewModel();

            vm.Messages = msgRepo.Messages;

            Collection<WallMessage> ModelMsgs = new Collection<WallMessage>();
            foreach(var m in vm.Messages.Reverse())
            {
                var mg = new WallMessage()
                {
                     Message = m.Message,
                     Name = m.Name,
                     TimeStamp = m.TimeStamp
                };

                ModelMsgs.Add(mg);
            }

            vm.Messages = ModelMsgs;

            return View(vm);
        }


        // GET: Wall/Create
        [ValidateAntiForgeryToken]
        [HttpPost]  
        public ActionResult Create(WallMessage message)
        {
            try
            {
                var msg = new WallMessage()
                {
                    Name = message.Name,
                    Message = message.Message,
                    TimeStamp = DateTime.Now
                };

               msgRepo.Messages.Add(msg);
               message.Message = string.Empty;

               WallViewModel vm = new WallViewModel(message, msgRepo.Messages);
                

                return View("Index", vm);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Wall/Create
        [ValidateAntiForgeryToken]
        // [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var msg = new WallMessage()
                {
                    Name = collection["message.Name"],
                    Message = collection["message.Message"],
                    TimeStamp = DateTime.Now
                };

                msgRepo.Messages.Add(msg);

                //return View("Index", _messages);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult ClearAll()
        {
            try
            {
                msgRepo.Messages.Clear();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

TalkingWall/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg-info">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Talking Wall", "Index", "Wall", new { area = "" }, new { @class = "navbar-brand" })

                <a class="navbar-brand" href="#home">
                    <span class="glyphicon glyphicon-home"></span>
                    <span class="text">Home</span>
                </a>
                <a class="navbar-brand" href="#about">
                    <span class="glyphicon glyphicon-bullhorn"></span>
                    <span class="text">About</span>
                </a>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
            <!--/.navbar-collapse -->
        </div>
    </div>

    <div class="container body-content" style="margin-top:20px;" ">
        <div class=" row">
        <div class="col-md-3">
            @RenderSection("LeftCol", false)
        </div>
        <div class="col-md-9 content-main">
            @RenderBody()
        </div>
    </div> 

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TalkingWall/Views/View.cshtml
@model TalkingWall.Domain.WallMessage

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WallMessage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TalkingWall/Views/Wall/Index.cshtml
@model TalkingWall.ViewModels.WallViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "The Talking Wall";
}

<div class="row">
    <div class="col-lg-6 col-lg-offset-1 highlight">
        <div class="h3">The Wall<hr /></div>
        @foreach (var msg in @Model.Messages.Reverse())
        {
            <div class="row">
                <div class="row">
                    <div class="h4 col-lg-10 col-lg-offset-1">
                        @msg.Message
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-lg-offset-1 text-muted">
                        @msg.Name
                    </div>
                    <div class="col-lg-4 col-lg-offset-3 text-muted">
                        @msg.TimeStamp
                    </div>
                </div>
            </div>
            <div class="divider" style="color:orangered;">
                <hr style="width:90%; margin-bottom:20px;" />
            </div>
        }


        @section LeftCol {

            <div class="module">
                @* using (Html.BeginForm("Create", "Wall", FormMethod.Post, new { name = "message" })) *@
                <form action="/Wall/Create" method="post" name="WallMessage">
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <div class="container">
                        <legend class="col-lg-offset-1">Post to Wall</legend>
                        <div class="form-group">
                            <div class="col-lg-offset-1">
                                <textarea class="form-control" placeholder="Message" id="Message" name="message.Message">@Model.Message</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-1">
                                <input type="text" id="Name" class="form-control" placeholder="User Name" name="message.Name" value="@Model.Name">
                                <input type="submit" style="margin-top: 5px; float: right;" id="PostButton" class="btn btn-success" value="Post">
                            </div>
                        </div>
</div>
                    </fieldset>
                </form>
            </div>
        }